#!/usr/bin/python3

import argparse
import C_build_script.make as make
import shutil
import os
import sys

from pathlib import Path

def main():

    argparser = argparse.ArgumentParser()
    argparser.add_argument("-s", action='store', type=str, metavar="SOURCE",   help="Source file to generate executable from")
    argparser.add_argument("-o", action='store', type=str, metavar="EXE NAME", help="Executable output name")
    argparser.add_argument("-d", action='store_true', help="Sets build to debug mode")
    argparser.add_argument("-c", action='store_true', help="Cleans all output files")
    args = argparser.parse_args()

    if args.c:
        if os.path.exists("bin"):
            print("Removing 'bin/'")
            shutil.rmtree("bin")
        if os.path.exists("objects"):
            print("Removing 'objects/'")
            shutil.rmtree("objects")
        if os.path.exists("objects-debug"):
            print("Removing 'objects-debug/'")
            shutil.rmtree("objects-debug")

    dependency_mapping = {

    }

    # Copy folders directly into bin
    resource_mappings = {
        "res/images": "",
        "res/fonts":  "",
        "res/sounds": ""
    }


    if args.s:
        config = {
            "COMPILER":         "clang++",
            "LINKER_FLAGS":     "-lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer",
            "SOURCE_DIR":       "src/",
            "SOURCE_MAIN":      Path(args.s).relative_to("src"),
            "RESOURCES":        resource_mappings,
            "DEPEND_MAPPING":   dependency_mapping
        }

        # If we're on windows, we'll just provide the necessary headers and libs
        if sys.platform == "win32":
            libpath = "lib/windows/SDL2-libs"

            config["OTHER_INCLUDE_PATHS"] = [
                f"{libpath}/SDL2/include",
                f"{libpath}/SDL2/include/SDL2",
                f"{libpath}/SDL2_image/include",
                f"{libpath}/SDL2_mixer/include",
                f"{libpath}/SDL2_ttf/include",
            ]
            config["OTHER_LIB_PATHS"] = [
                f"{libpath}/SDL2/lib/x64/",
                f"{libpath}/SDL2_image/lib/x64/",
                f"{libpath}/SDL2_mixer/lib/x64/",
                f"{libpath}/SDL2_ttf/lib/x64/",
            ]
            config["LINKER_FLAGS"] = f"-Xlinker /subsystem:windows -lShell32 -lSDL2main " + config["LINKER_FLAGS"]
            
            # Find all DLLs and copy them into bin
            resource_mappings[f"{libpath}/**/x64/**/*.dll"] = ""

        if args.d:
            config["COMPILER_FLAGS"] = "-std=c++17 -Wall -Wextra -Wpedantic -g -DDEBUG -Wno-language-extension-token"
            config["OBJECT_DIR"]     = "./objects-debug/"
            config["EXE_FILE"]       = "prog-debug"
        else:
            config["COMPILER_FLAGS"] = "-std=c++17 -Wall -Wextra -Wpedantic -O3 -Wno-language-extension-token"
            config["OBJECT_DIR"]     = "./objects/"
            config["EXE_FILE"]       = "prog"

        if args.o:
            config["EXE_FILE"]      = args.o

        if sys.platform == "win32":
            config["EXE_FILE"] += ".exe"

        make.parse_dict(config)
        make.execute("build")


if __name__ == "__main__":
    main()
