#!/usr/bin/python3

import argparse
import C_build_script.make as make
import shutil
import os
import sys

from pathlib import Path

def main():

    argparser = argparse.ArgumentParser()
    argparser.add_argument("-s", action='store', type=str, metavar="SOURCE",   help="Source file to generate executable from")
    argparser.add_argument("-o", action='store', type=str, metavar="EXE NAME", help="Executable output name")
    argparser.add_argument("-d", action='store_true', help="Sets build to debug mode")
    argparser.add_argument("-c", action='store_true', help="Cleans all output files")
    args = argparser.parse_args()

    if args.c:
        if os.path.exists("bin"):
            print("Removing 'bin/'")
            shutil.rmtree("bin")
        if os.path.exists("objects"):
            print("Removing 'objects/'")
            shutil.rmtree("objects")
        if os.path.exists("objects-debug"):
            print("Removing 'objects-debug/'")
            shutil.rmtree("objects-debug")

    dependency_mapping = {

    }

    # Copy folders directly into bin
    resource_mappings = {
        "res/images": "",
        "res/fonts":  "",
        "res/sounds": ""
    }


    if args.s:
        config = {
            "COMPILER":         "clang++",
            "LINKER_FLAGS":     "-lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer",
            "SOURCE_DIR":       "src/",
            "SOURCE_MAIN":      Path(args.s).relative_to("src"),
            "RESOURCES":        resource_mappings,
            "DEPEND_MAPPING":   dependency_mapping
        }

        # If we're on windows, we'll just provide the necessary headers and libs
        if sys.platform == "win32":
            config["OTHER_INCLUDE_PATHS"] = [
                "lib/windows/SDL2/include",
                "lib/windows/SDL2/include/SDL2",
                "lib/windows/SDL2_image/include",
                "lib/windows/SDL2_mixer/include",
                "lib/windows/SDL2_ttf/include",
            ]
            config["OTHER_LIB_PATHS"] = [
                "lib/windows/SDL2/lib/x64/",
                "lib/windows/SDL2_image/lib/x64/",
                "lib/windows/SDL2_mixer/lib/x64/",
                "lib/windows/SDL2_ttf/lib/x64/",
            ]
            config["LINKER_FLAGS"] = f"-Xlinker /subsystem:windows -lShell32 -lSDL2main " + config["LINKER_FLAGS"]
            
            # Find all DLLs and copy them into bin
            resource_mappings["lib/windows/**/x64/**/*.dll"] = ""

            # resource_mappings["lib/windows/SDL2/lib/x64/SDL2.dll"] = "SDL2.dll"

            # resource_mappings["lib/windows/SDL2_image/lib/x64/libjpeg-9.dll"]   = "libjpeg-9.dll"
            # resource_mappings["lib/windows/SDL2_image/lib/x64/libpng16-16.dll"] = "libpng16-16.dll"
            # resource_mappings["lib/windows/SDL2_image/lib/x64/libtiff-5.dll"]   = "libtiff-5.dll"
            # resource_mappings["lib/windows/SDL2_image/lib/x64/libwebp-7.dll"]   = "libwebp-7.dll"
            # resource_mappings["lib/windows/SDL2_image/lib/x64/SDL2_image.dll"]  = "SDL2_image.dll"

            # resource_mappings["lib/windows/SDL2_mixer/lib/x64/libFLAC-8.dll"]       = "libFLAC-8.dll"
            # resource_mappings["lib/windows/SDL2_mixer/lib/x64/libmodplug-1.dll"]    = "libmodplug-1.dll"
            # resource_mappings["lib/windows/SDL2_mixer/lib/x64/libmpg123-0.dll"]     = "libmpg123-0.dll"
            # resource_mappings["lib/windows/SDL2_mixer/lib/x64/libogg-0.dll"]        = "libogg-0.dll"
            # resource_mappings["lib/windows/SDL2_mixer/lib/x64/libopus-0.dll"]       = "libopus-0.dll"
            # resource_mappings["lib/windows/SDL2_mixer/lib/x64/libopusfile-0.dll"]   = "libopusfile-0.dll"
            # resource_mappings["lib/windows/SDL2_mixer/lib/x64/libvorbis-0.dll"]     = "libvorbis-0.dll"
            # resource_mappings["lib/windows/SDL2_mixer/lib/x64/libvorbisfile-3.dll"] = "libvorbisfile-3.dll"
            # resource_mappings["lib/windows/SDL2_mixer/lib/x64/SDL2_mixer.dll"]      = "SDL2_mixer.dll"

            # resource_mappings["lib/windows/SDL2_ttf/lib/x64/libfreetype-6.dll"] = "libfreetype-6.dll"
            # resource_mappings["lib/windows/SDL2_ttf/lib/x64/SDL2_ttf.dll"]      = "SDL2_ttf.dll"
            # resource_mappings["lib/windows/SDL2_ttf/lib/x64/zlib1.dll"]         = "zlib1.dll"

        if args.d:
            config["COMPILER_FLAGS"] = "-std=c++17 -Wall -Wextra -Wpedantic -g -DDEBUG -Wno-language-extension-token"
            config["OBJECT_DIR"]     = "./objects-debug/"
            config["EXE_FILE"]       = "prog-debug"
        else:
            config["COMPILER_FLAGS"] = "-std=c++17 -Wall -Wextra -Wpedantic -O3 -Wno-language-extension-token"
            config["OBJECT_DIR"]     = "./objects/"
            config["EXE_FILE"]       = "prog"

        if args.o:
            config["EXE_FILE"]      = args.o

        if sys.platform == "win32":
            config["EXE_FILE"] += ".exe"

        make.parse_dict(config)
        make.execute("build")


if __name__ == "__main__":
    main()
